### ISSUE TITLE
Loss value might be negative. Is it ok?

### ISSUE THREAD

**Issue by awkrail** [majumderb/recipe-personalization#4]
Hi, I've read your paper. It's very nice and interesting.
I would like to ask you a question about an evaluation of recipe level coherence using an absolute order network.

In your code at recipe-personalization/recipe_gen/analysis/absolute_order_teacher.py L77, the cosine similarity loss is calculated as:
```python
cos_similarity = F.cosine_similarity(repr_1, repr_2, dim=1)
```
I replicated it and found that the loss value would be negative after training.
Is it acceptable?

**Comment by shuyangli94** [comment]
Thanks for your interest!
The absolute order teacher minimizes the cosine similarity (maximizes cosine distance) between the forward and backward encoded representations of recipe steps (intuitively, since recipes are ordered procedural texts, the absolute order evaluator learns to produce representations that respect order by explicitly maximizing distance between correctly-ordered and "disordered" examples).

Cosine similarity can be between `-1` and `1`, where `-1` indicates strong dissimilarity - which we want the teacher to learn (to minimize cosine sim). In short, this is expected :)
